// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// poisson_deviance
NumericVector poisson_deviance(const NumericVector& y, const NumericVector& mu);
RcppExport SEXP _kmeansPoi_poisson_deviance(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_deviance(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// run_kmeans
List run_kmeans(const NumericMatrix& Y, const NumericVector& size_factors, const NumericMatrix& centers_start, double min_mu, int max_iter, double tolerance, bool verbose);
RcppExport SEXP _kmeansPoi_run_kmeans(SEXP YSEXP, SEXP size_factorsSEXP, SEXP centers_startSEXP, SEXP min_muSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type size_factors(size_factorsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type centers_start(centers_startSEXP);
    Rcpp::traits::input_parameter< double >::type min_mu(min_muSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(run_kmeans(Y, size_factors, centers_start, min_mu, max_iter, tolerance, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kmeansPoi_poisson_deviance", (DL_FUNC) &_kmeansPoi_poisson_deviance, 2},
    {"_kmeansPoi_run_kmeans", (DL_FUNC) &_kmeansPoi_run_kmeans, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_kmeansPoi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
