# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fuse_ints_for_double <- function(exp, sig) {
    .Call(`_kmeansPoi_fuse_ints_for_double`, exp, sig)
}

get_LOG_LOOKUP_TABLE_EXPONENTIAL_LENGTH <- function() {
    .Call(`_kmeansPoi_get_LOG_LOOKUP_TABLE_EXPONENTIAL_LENGTH`)
}

get_LOG_LOOKUP_TABLE_SIGNIFCAND_LENGTH <- function() {
    .Call(`_kmeansPoi_get_LOG_LOOKUP_TABLE_SIGNIFCAND_LENGTH`)
}

get_exponent_as_integer_from_double <- function(x) {
    .Call(`_kmeansPoi_get_exponent_as_integer_from_double`, x)
}

get_significand_as_integer_from_double <- function(x) {
    .Call(`_kmeansPoi_get_significand_as_integer_from_double`, x)
}

log_approx <- function(x) {
    .Call(`_kmeansPoi_log_approx`, x)
}

log_approx2 <- function(x) {
    .Call(`_kmeansPoi_log_approx2`, x)
}

benchmark_log <- function(x) {
    .Call(`_kmeansPoi_benchmark_log`, x)
}

benchmark_log_approx <- function(x) {
    .Call(`_kmeansPoi_benchmark_log_approx`, x)
}

benchmark_log_approx2 <- function(x) {
    .Call(`_kmeansPoi_benchmark_log_approx2`, x)
}

poisson_deviance <- function(y, mu) {
    .Call(`_kmeansPoi_poisson_deviance`, y, mu)
}

poisson_deviance_opt <- function(y, mu) {
    .Call(`_kmeansPoi_poisson_deviance_opt`, y, mu)
}

run_kmeans <- function(Y, size_factors, centers_start, min_mu, max_iter, tolerance, verbose) {
    .Call(`_kmeansPoi_run_kmeans`, Y, size_factors, centers_start, min_mu, max_iter, tolerance, verbose)
}

kmeans_pp_initialization <- function(Y, size_factors, k, min_mu) {
    .Call(`_kmeansPoi_kmeans_pp_initialization`, Y, size_factors, k, min_mu)
}

