# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poisson_deviance <- function(y, mu) {
    .Call(`_kmeansPoi_poisson_deviance`, y, mu)
}

run_kmeans <- function(Y, size_factors, centers_start, min_mu, max_iter, tolerance, verbose) {
    .Call(`_kmeansPoi_run_kmeans`, Y, size_factors, centers_start, min_mu, max_iter, tolerance, verbose)
}

